/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as CostRouteImport } from './routes/cost'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsNameRouteImport } from './routes/skills_.$name'
import { Route as SessionsCompareRouteImport } from './routes/sessions_.compare'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNameRoute = SkillsNameRouteImport.update({
  id: '/skills_/$name',
  path: '/skills/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCompareRoute = SessionsCompareRouteImport.update({
  id: '/sessions_/compare',
  path: '/sessions/compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/cost': typeof CostRoute
  '/skills': typeof SkillsRoute
  '/sessions/compare': typeof SessionsCompareRoute
  '/skills/$name': typeof SkillsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/cost': typeof CostRoute
  '/skills': typeof SkillsRoute
  '/sessions/compare': typeof SessionsCompareRoute
  '/skills/$name': typeof SkillsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/cost': typeof CostRoute
  '/skills': typeof SkillsRoute
  '/sessions_/compare': typeof SessionsCompareRoute
  '/skills_/$name': typeof SkillsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/cost'
    | '/skills'
    | '/sessions/compare'
    | '/skills/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/cost'
    | '/skills'
    | '/sessions/compare'
    | '/skills/$name'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/alerts'
    | '/cost'
    | '/skills'
    | '/sessions_/compare'
    | '/skills_/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  CostRoute: typeof CostRoute
  SkillsRoute: typeof SkillsRoute
  SessionsCompareRoute: typeof SessionsCompareRoute
  SkillsNameRoute: typeof SkillsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills_/$name': {
      id: '/skills_/$name'
      path: '/skills/$name'
      fullPath: '/skills/$name'
      preLoaderRoute: typeof SkillsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/compare': {
      id: '/sessions_/compare'
      path: '/sessions/compare'
      fullPath: '/sessions/compare'
      preLoaderRoute: typeof SessionsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  CostRoute: CostRoute,
  SkillsRoute: SkillsRoute,
  SessionsCompareRoute: SessionsCompareRoute,
  SkillsNameRoute: SkillsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
