"""initial schema (15 tables).

Revision ID: 0001_initial
Revises: -
Create Date: 2026-04-25

Generated via `alembic revision --autogenerate` against SQLModel.metadata
(populated by cmc/db/models/__init__.py importing all 15 model modules per
Pitfall 2). Hand-verified for:
- All 15 op.create_table blocks present
- ForeignKey constraints with correct ondelete (CASCADE / SET NULL)
- All indexes from __table_args__ present (via op.batch_alter_table per env.py)
- UNIQUE constraints (uq_token_usage_*, uq_mcp_stats_*, uq_notification_log_*,
  uq_schedules_name, uq_tools_tool_use_id, uq_activities_day_kind)
- Partial unique index uq_decisions_pending_dedup_key with
  sqlite_where=text("status = 'pending'") (HITL-02)
- downgrade() reverses everything in dependency order

Manual edits over autogenerate output:
- Stable revision id "0001_initial" (autogenerate produced d18b32ad99e5)
- Added explicit `import sqlmodel` at top (autogenerate references
  sqlmodel.sql.sqltypes.AutoString without emitting the import)
- Added _column_exists helper for FOUND-03 (idempotent ADD COLUMN check)
"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def _column_exists(table: str, column: str) -> bool:
    """FOUND-03: idempotent column-exists check for future ADD COLUMN migrations.

    Future revisions can import this helper as:
        from migrations.versions.0001_initial import _column_exists
    or copy-paste the function into their own revision (it has no module-level state).

    Returns True if `column` is present on `table` according to the live SQLAlchemy
    inspector. Use to guard `op.add_column(...)` so a re-run does not error.
    """
    bind = op.get_bind()
    inspector = inspect(bind)
    return any(c["name"] == column for c in inspector.get_columns(table))


def upgrade() -> None:
    """Upgrade schema — create all 15 tables."""
    # ### commands auto generated by Alembic - hand-verified ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day", "kind", name="uq_activities_day_kind"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index("idx_activities_day_desc", ["day"], unique=False)

    op.create_table(
        "mcp_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("latency_p50_ms", sa.Float(), nullable=True),
        sa.Column("latency_p95_ms", sa.Float(), nullable=True),
        sa.Column("latency_max_ms", sa.Float(), nullable=True),
        sa.Column("schema_size_bytes", sa.Integer(), nullable=True),
        sa.Column("source_priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_name", "tool_name", name="uq_mcp_stats_server_tool"),
    )
    with op.batch_alter_table("mcp_stats", schema=None) as batch_op:
        batch_op.create_index("idx_mcp_stats_server", ["server_name"], unique=False)

    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "kind", "entity_id", "chat_id", name="uq_notification_log_kind_entity_chat"
        ),
    )
    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.create_index("idx_notification_log_sent_at_desc", ["sent_at"], unique=False)
        batch_op.create_index(
            "idx_notification_log_snoozed_until", ["snoozed_until"], unique=False
        )

    op.create_table(
        "otel_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("metric_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attrs", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otel_metrics", schema=None) as batch_op:
        batch_op.create_index("idx_otel_metrics_name_ts", ["metric_name", "ts"], unique=False)
        batch_op.create_index("idx_otel_metrics_ts_desc", ["ts"], unique=False)

    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cron", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("task_template", sa.JSON(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_schedules_name"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(
            "idx_schedules_enabled_next_run", ["enabled", "next_run_at"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.Column("jsonl_mtime", sa.DateTime(), nullable=False),
        sa.Column("jsonl_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cwd", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tokens_input", sa.Integer(), nullable=False),
        sa.Column("tokens_output", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_read", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_create", sa.Integer(), nullable=False),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("idx_sessions_cwd", ["cwd"], unique=False)
        batch_op.create_index("idx_sessions_ended_at", ["ended_at"], unique=False)
        batch_op.create_index("idx_sessions_model", ["model"], unique=False)
        batch_op.create_index("idx_sessions_started_at_desc", ["started_at"], unique=False)
        batch_op.create_index("idx_sessions_synced_at", ["synced_at"], unique=False)

    op.create_table(
        "skills",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("environment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_invocable", sa.Boolean(), nullable=False),
        sa.Column("autonomy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frontmatter", sa.JSON(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index("idx_skills_autonomy", ["autonomy"], unique=False)
        batch_op.create_index(
            "idx_skills_env_user_invocable", ["environment", "user_invocable"], unique=False
        )

    op.create_table(
        "system_state",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )

    op.create_table(
        "token_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tokens_input", sa.Integer(), nullable=False),
        sa.Column("tokens_output", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_read", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_create", sa.Integer(), nullable=False),
        sa.Column("sessions_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day", "model", "source", name="uq_token_usage_day_model_source"),
    )
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.create_index("idx_token_usage_day_desc", ["day"], unique=False)

    op.create_table(
        "live_state",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_tool", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("live_state", schema=None) as batch_op:
        batch_op.create_index(
            "idx_live_state_last_activity_desc", ["last_activity_at"], unique=False
        )

    op.create_table(
        "otel_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("event_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("attrs_mcp_server", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attrs_mcp_tool", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otel_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_otel_events_attrs_mcp", ["attrs_mcp_server", "attrs_mcp_tool"], unique=False
        )
        batch_op.create_index(
            "idx_otel_events_event_name_ts", ["event_name", "ts"], unique=False
        )
        batch_op.create_index(
            "idx_otel_events_session_id_ts", ["session_id", "ts"], unique=False
        )
        batch_op.create_index("idx_otel_events_ts_desc", ["ts"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("quadrant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approval", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("risk", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("execution_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("stdout_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("idx_tasks_pid", ["pid"], unique=False)
        batch_op.create_index("idx_tasks_quadrant_status", ["quadrant", "status"], unique=False)
        batch_op.create_index("idx_tasks_schedule_id", ["schedule_id"], unique=False)
        batch_op.create_index(
            "idx_tasks_status_priority_scheduled",
            ["status", "priority", "scheduled_for"],
            unique=False,
        )

    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_use_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("input_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mcp_server_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mcp_tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_use_id", name="uq_tools_tool_use_id"),
    )
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tools_mcp_server_tool", ["mcp_server_name", "mcp_tool_name"], unique=False
        )
        batch_op.create_index(
            "idx_tools_name_started_at", ["tool_name", "started_at"], unique=False
        )
        batch_op.create_index("idx_tools_session_id", ["session_id"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.Column("answered_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.session_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index("idx_decisions_session_id", ["session_id"], unique=False)
        batch_op.create_index(
            "idx_decisions_status_created", ["status", "created_at"], unique=False
        )
        batch_op.create_index("idx_decisions_task_id", ["task_id"], unique=False)
        # HITL-02: partial UNIQUE — autogenerate emits this correctly with sqlite_where
        batch_op.create_index(
            "uq_decisions_pending_dedup_key",
            ["dedup_key"],
            unique=True,
            sqlite_where=sa.text("status = 'pending'"),
        )

    op.create_table(
        "inbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("reply", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("replied_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.session_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.create_index("idx_inbox_read_created", ["read", "created_at"], unique=False)
        batch_op.create_index("idx_inbox_session_id", ["session_id"], unique=False)
        batch_op.create_index("idx_inbox_task_id", ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema — drop all 15 tables in reverse-dependency order."""
    # ### commands auto generated by Alembic - hand-verified ###
    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.drop_index("idx_inbox_task_id")
        batch_op.drop_index("idx_inbox_session_id")
        batch_op.drop_index("idx_inbox_read_created")
    op.drop_table("inbox")

    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_decisions_pending_dedup_key", sqlite_where=sa.text("status = 'pending'")
        )
        batch_op.drop_index("idx_decisions_task_id")
        batch_op.drop_index("idx_decisions_status_created")
        batch_op.drop_index("idx_decisions_session_id")
    op.drop_table("decisions")

    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_index("idx_tools_session_id")
        batch_op.drop_index("idx_tools_name_started_at")
        batch_op.drop_index("idx_tools_mcp_server_tool")
    op.drop_table("tools")

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_tasks_status_priority_scheduled")
        batch_op.drop_index("idx_tasks_schedule_id")
        batch_op.drop_index("idx_tasks_quadrant_status")
        batch_op.drop_index("idx_tasks_pid")
    op.drop_table("tasks")

    with op.batch_alter_table("otel_events", schema=None) as batch_op:
        batch_op.drop_index("idx_otel_events_ts_desc")
        batch_op.drop_index("idx_otel_events_session_id_ts")
        batch_op.drop_index("idx_otel_events_event_name_ts")
        batch_op.drop_index("idx_otel_events_attrs_mcp")
    op.drop_table("otel_events")

    with op.batch_alter_table("live_state", schema=None) as batch_op:
        batch_op.drop_index("idx_live_state_last_activity_desc")
    op.drop_table("live_state")

    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.drop_index("idx_token_usage_day_desc")
    op.drop_table("token_usage")

    op.drop_table("system_state")

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index("idx_skills_env_user_invocable")
        batch_op.drop_index("idx_skills_autonomy")
    op.drop_table("skills")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_sessions_synced_at")
        batch_op.drop_index("idx_sessions_started_at_desc")
        batch_op.drop_index("idx_sessions_model")
        batch_op.drop_index("idx_sessions_ended_at")
        batch_op.drop_index("idx_sessions_cwd")
    op.drop_table("sessions")

    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index("idx_schedules_enabled_next_run")
    op.drop_table("schedules")

    with op.batch_alter_table("otel_metrics", schema=None) as batch_op:
        batch_op.drop_index("idx_otel_metrics_ts_desc")
        batch_op.drop_index("idx_otel_metrics_name_ts")
    op.drop_table("otel_metrics")

    with op.batch_alter_table("notification_log", schema=None) as batch_op:
        batch_op.drop_index("idx_notification_log_snoozed_until")
        batch_op.drop_index("idx_notification_log_sent_at_desc")
    op.drop_table("notification_log")

    with op.batch_alter_table("mcp_stats", schema=None) as batch_op:
        batch_op.drop_index("idx_mcp_stats_server")
    op.drop_table("mcp_stats")

    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index("idx_activities_day_desc")
    op.drop_table("activities")
    # ### end Alembic commands ###
